services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      # Передает переменные окружения из .env файла
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Передаем URL бэкенда, доступный из браузера на хост-машине
        - VITE_WS_URL_ARG=ws://localhost:8000/ws/analysis
    ports:
      - "5173:80"
    depends_on:
      - backend
