services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Синхронизирует исходный код для live-reloading
      - ./backend/src:/app
    env_file:
      # Передает переменные окружения из .env файла
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
