services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Порт больше не нужно пробрасывать наружу,
    # т.к. Nginx будет общаться с ним внутри Docker-сети.
    # ports:
    #   - "8013:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Теперь WebSocket-клиент подключается к тому же домену,
        # что и само приложение, т.к. Nginx будет проксировать запрос.
        - VITE_WS_URL_ARG=wss://ddf7b09d269a.ngrok-free.app/ws/analysis
    ports:
      # Мы пробрасываем только порт Nginx (frontend)
      - "5173:80"
    depends_on:
      - backend
